document.head.insertAdjacentHTML('beforeend','<style>.payment-qr{display:block;width:210px;height:210px;object-fit:contain;margin:14px auto;border:1px solid #ddd;border-radius:12px}.account-card{text-align:center;background:#eef5f2;border-radius:13px;padding:12px;margin:10px 0}.account-card b{font-size:20px}#qrSettingPreview img{width:150px;height:150px;object-fit:contain}</style>');
db.settings.adminPassword=db.settings.adminPassword||'admin';let orderDiscount=0,orderNote='',settingsUnlocked=false,pendingQr=db.settings.qrImage||'';
const form=$('#settings .form');form.insertAdjacentHTML('beforeend','<label class="field"><span>ชื่อบัญชีรับเงิน</span><input id="accountName"></label><label class="field"><span>เบอร์โทรศัพท์</span><input id="accountPhone"></label><label class="field full"><span>เลขบัญชี / PromptPay</span><input id="accountNumber"></label><label class="field full"><span>รูป QR Code รับเงิน</span><input id="qrImageInput" type="file" accept="image/*"><div id="qrSettingPreview"></div></label><label class="field full"><span>เปลี่ยนรหัสตั้งค่า</span><input id="adminPassword" type="password" placeholder="รหัสเริ่มต้น admin"></label>');
$('.cart h2').insertAdjacentHTML('afterend','<small>เลขบิล <b id="currentBillNo"></b></small>');$('#hold').insertAdjacentHTML('beforebegin','<button class="btn secondary" id="discountBtn">ส่วนลด</button><button class="btn secondary" id="orderNoteBtn">หมายเหตุ</button>');
$('.qr').outerHTML='<div id="paymentQr"><div class="qr"></div></div><div id="paymentAccount" class="account-card"></div>';
for(const [id,key] of [['accountName','accountName'],['accountPhone','accountPhone'],['accountNumber','accountNumber']])$('#'+id).value=db.settings[key]||'';
function nextBill(){let day=new Date().toISOString().slice(0,10).replaceAll('-',''),n=db.orders.filter(o=>o.no?.startsWith('B'+day)).length+1;return `B${day}-${String(n).padStart(4,'0')}`}
function showBill(){$('#currentBillNo').textContent=nextBill()}function showQr(){let s=db.settings;$('#paymentQr').innerHTML=s.qrImage?`<img class="payment-qr" src="${s.qrImage}">`:'<div class="qr"></div>';$('#paymentAccount').innerHTML=`<b>${s.accountName||'ยังไม่ได้ตั้งชื่อบัญชี'}</b><div>${s.accountPhone?'โทร '+s.accountPhone:''}</div><div>${s.accountNumber?'เลขบัญชี / PromptPay: '+s.accountNumber:'กรุณาตั้งค่าเลขบัญชี'}</div>`}
let baseTotals=totals;totals=()=>{let t=baseTotals(),d=Math.min(orderDiscount,t.sub);return {...t,discount:d,total:Math.max(0,t.total-d)}};let baseRender=renderCart;renderCart=()=>{baseRender();let t=totals(),r=$('#discountRow');if(!r){r=document.createElement('div');r.id='discountRow';$('#serviceRow').before(r)}r.innerHTML=`<span>ส่วนลด</span><b>-${money(t.discount)}</b>`;r.hidden=!t.discount;$('#grand').textContent=money(t.total);showBill()};
let baseComplete=complete;complete=()=>{let no=nextBill(),before=db.orders.length,note=orderNote,disc=orderDiscount;baseComplete();if(db.orders.length>before){let o=db.orders.at(-1);o.no=no;o.note=note;o.discount=disc;save();orderDiscount=0;orderNote='';showBill()}};
$('#discountBtn').onclick=()=>{let v=prompt('ส่วนลดทั้งบิล (บาท)',orderDiscount);if(v!==null&&!isNaN(v)&&+v>=0){orderDiscount=+v;renderCart()}};$('#orderNoteBtn').onclick=()=>{let v=prompt('หมายเหตุออเดอร์',orderNote);if(v!==null)orderNote=v.trim()};
let sn=$('.nav[data-page="settings"]'),snClick=sn.onclick;sn.onclick=e=>{if(!settingsUnlocked){let p=prompt('กรอกรหัสผู้ดูแลเพื่อเข้าตั้งค่า');if(p!==db.settings.adminPassword)return toast('รหัสไม่ถูกต้อง');settingsUnlocked=true}snClick.call(sn,e)};
$('#qrImageInput').onchange=async e=>{try{pendingQr=await resizeImage(e.target.files[0]);$('#qrSettingPreview').innerHTML=`<img src="${pendingQr}">`}catch{toast('ไม่สามารถอ่านรูป QR ได้')}};if(pendingQr)$('#qrSettingPreview').innerHTML=`<img src="${pendingQr}">`;
let saveClick=$('#saveSettings').onclick;$('#saveSettings').onclick=()=>{db.settings.accountName=$('#accountName').value.trim();db.settings.accountPhone=$('#accountPhone').value.trim();db.settings.accountNumber=$('#accountNumber').value.trim();db.settings.qrImage=pendingQr;if($('#adminPassword').value)db.settings.adminPassword=$('#adminPassword').value;saveClick();save();showQr()};$$('[data-pay]').forEach(b=>{let f=b.onclick;b.onclick=()=>{f();showQr()}});showBill();showQr();renderCart();
