db.expenses=db.expenses||[];db.finance=db.finance||{rentMode:'daily',dailyRent:100,monthlyRent:0,annualRent:2500};
let crab=db.products.find(p=>p.id===1),crabPack=db.products.find(p=>p.id===2),fish=db.products.find(p=>p.id===3);if(!db.finance.migrated){Object.assign(crab,{cost:10,stock:7,min:7,sharedKey:'crab',stockPerSale:1});Object.assign(crabPack,{cost:70,stock:1,min:1,sharedKey:'crab',stockPerSale:7});Object.assign(fish,{cost:70,stock:1,min:1});db.expenses.push({id:Date.now(),date:new Date().toISOString(),type:'ค่าขนส่งสินค้า',amount:120,note:'สต๊อกรอบแรก'},{id:Date.now()+1,date:new Date().toISOString(),type:'ค่าน้ำมันไปรับสินค้า',amount:500,note:'สต๊อกรอบแรก'});db.finance.migrated=true;save()}
function syncShared(){if(crab&&crabPack)crabPack.stock=Math.floor(crab.stock/7)}syncShared();
$('#report .cards').insertAdjacentHTML('beforeend','<div class="metric">รายจ่ายรวม<b id="expenseTotal">฿0</b></div><div class="metric">กำไรสุทธิ<b id="netProfit">฿0</b></div>');
$('#report').insertAdjacentHTML('beforeend','<div class="box"><div class="top"><h3>บันทึกรายจ่าย</h3></div><div class="form"><label class="field"><span>ประเภทรายจ่าย</span><select id="expenseType"><option>ค่าน้ำมันไปขาย</option><option>ค่าน้ำมันไปรับสินค้า</option><option>ค่าขนส่งสินค้า</option><option>ค่าเช่าที่</option><option>ค่าวัตถุดิบ</option><option>ค่าใช้จ่ายอื่น</option></select></label><label class="field"><span>จำนวนเงิน</span><input id="expenseAmount" type="number" min="0"></label><label class="field"><span>วันที่และเวลา</span><input id="expenseDate" type="datetime-local"></label><label class="field"><span>หมายเหตุ</span><input id="expenseNote"></label></div><button class="btn primary" id="addExpense">บันทึกรายจ่าย</button><div id="expenseHistory"></div></div>');
$('#settings .form').insertAdjacentHTML('beforeend','<label class="field"><span>รูปแบบค่าเช่าที่</span><select id="rentMode"><option value="daily">รายวัน</option><option value="monthly">รายเดือน</option><option value="none">ไม่มีรายวัน/รายเดือน</option></select></label><label class="field"><span>ค่าเช่ารายวัน</span><input id="dailyRent" type="number"></label><label class="field"><span>ค่าเช่ารายเดือน</span><input id="monthlyRent" type="number"></label><label class="field"><span>ค่าเช่ารายปี</span><input id="annualRent" type="number"></label>');
for(let k of ['rentMode','dailyRent','monthlyRent','annualRent'])$('#'+k).value=db.finance[k];$('#expenseDate').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
function expenseInPeriod(){let now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1),actual=db.expenses.filter(x=>new Date(x.date)>=start).reduce((s,x)=>s+x.amount,0),rent=db.finance.rentMode==='monthly'?db.finance.monthlyRent:(db.finance.rentMode==='daily'?db.finance.dailyRent*now.getDate():0),annual=db.finance.annualRent/12;return{actual,rent,annual,total:actual+rent+annual}}
function renderFinance(){let e=expenseInPeriod(),sales=db.orders.filter(o=>{let d=new Date(o.date),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).reduce((s,o)=>s+o.total,0),cost=db.orders.reduce((s,o)=>s+o.items.reduce((a,x)=>a+x.cost*x.qty,0),0);$('#expenseTotal').textContent=money(e.total);$('#netProfit').textContent=money(sales-cost-e.total);$('#expenseHistory').innerHTML='<h4>รายการล่าสุด</h4>'+db.expenses.slice().reverse().slice(0,20).map(x=>`<div class="line"><div><b>${x.type}</b><div>${new Date(x.date).toLocaleString('th-TH')} ${x.note?'· '+x.note:''}</div></div><div><b>${money(x.amount)}</b> <button class="btn danger" data-del-exp="${x.id}">ลบ</button></div></div>`).join('');$$('[data-del-exp]').forEach(b=>b.onclick=()=>{if(confirm('ลบรายจ่ายรายการนี้?')){db.expenses=db.expenses.filter(x=>x.id!=b.dataset.delExp);save();renderFinance()}})}
$('#addExpense').onclick=()=>{let amount=+$('#expenseAmount').value;if(!(amount>0))return toast('กรุณากรอกจำนวนเงิน');db.expenses.push({id:Date.now(),date:new Date($('#expenseDate').value).toISOString(),type:$('#expenseType').value,amount,note:$('#expenseNote').value.trim()});save();$('#expenseAmount').value='';$('#expenseNote').value='';renderFinance();toast('บันทึกรายจ่ายแล้ว')};
let financeSave=$('#saveSettings').onclick;$('#saveSettings').onclick=()=>{db.finance.rentMode=$('#rentMode').value;db.finance.dailyRent=+$('#dailyRent').value||0;db.finance.monthlyRent=+$('#monthlyRent').value||0;db.finance.annualRent=+$('#annualRent').value||0;financeSave();save();renderFinance()};
let financeComplete=complete;complete=()=>{let packs=cart.find(x=>x.id===2)?.qty||0,before=db.orders.length;financeComplete();if(db.orders.length>before&&packs){crab.stock=Math.max(0,crab.stock-packs*7);syncShared();save();renderAll();renderFinance()}};setTimeout(()=>{$('#confirmPay').onclick=complete},0);renderFinance();save();
