db.stockReceipts=db.stockReceipts||[];db.stockGroups.squid=db.stockGroups.squid||{name:'ปลาหมึก',qty:10000,baseUnit:'กรัม'};
if(!db.products.some(p=>p.stockGroup==='squid')){let id=Math.max(...db.products.map(p=>p.id))+1;db.products.push({id,name:'ปลาหมึก ถุง 5 ขีด',cat:'อาหาร',price:100,cost:0,stock:20,min:2,unit:'ถุง 5 ขีด',icon:'🦑',image:'',stockGroup:'squid',baseQty:500},{id:id+1,name:'ปลาหมึก 1 กิโลกรัม',cat:'อาหาร',price:190,cost:0,stock:10,min:1,unit:'กิโลกรัม',icon:'🦑',image:'',stockGroup:'squid',baseQty:1000});save()}
$('#saleMeasure').insertAdjacentHTML('beforeend','<option value="khid">ขีด</option>');$('#stockGroup').insertAdjacentHTML('beforeend','<option value="squid">ปลาหมึก (กรัม)</option>');
let productSaveReceive=$('#saveProduct').onclick;$('#saveProduct').onclick=()=>{let m=$('#saleMeasure').value,q=+$('#baseQty').value||1;productSaveReceive();let id=+$('#productId').value,p=db.products.find(x=>x.id===id)||(id?null:db.products.at(-1));if(p&&m==='khid'){p.baseQty=q*100;p.unit=`${q} ขีด`;syncGroupStocks();save();renderAll()}};
let productsReceive=renderProducts;renderProducts=()=>{productsReceive();$$('.product').forEach(b=>{let p=db.products.find(x=>x.id==b.dataset.id),small=b.locator?null:b.querySelector('small');if(!p||!small)return;let inCart=cart.find(x=>x.id===p.id)?.qty||0;if(p.stockGroup){let g=db.stockGroups[p.stockGroup],reserved=cart.filter(x=>x.stockGroup===p.stockGroup).reduce((s,x)=>s+x.baseQty*x.qty,0),remain=Math.max(0,g.qty-reserved),available=Math.floor(remain/p.baseQty);small.innerHTML=`ในตะกร้า <b>${inCart}</b> · เหลือ <b>${available}</b> ${p.unit||'หน่วย'}`}else small.innerHTML=`ในตะกร้า <b>${inCart}</b> · เหลือ <b>${Math.max(0,p.stock-inCart)}</b> ${p.unit||'ชิ้น'}`})};
let cartReceive=renderCart;renderCart=()=>{cartReceive();renderProducts()};
let stockReceive=renderStock;renderStock=()=>{stockReceive();let box=$('#groupStockInfo');if(!box)return;box.innerHTML=`<h3>รับสินค้าเข้าสต๊อก</h3><div class="form"><label class="field"><span>สินค้า</span><select id="receiveGroup">${Object.entries(db.stockGroups).map(([k,g])=>`<option value="${k}">${g.name}</option>`).join('')}</select></label><label class="field"><span>จำนวนรับเข้า</span><input id="receiveQty" type="number" min="0" step="0.001"></label><label class="field"><span>หน่วย</span><select id="receiveUnit"><option value="piece">กระดอง/ชิ้น</option><option value="g">กรัม</option><option value="khid">ขีด</option><option value="kg">กิโลกรัม</option></select></label><label class="field"><span>ต้นทุนรวมรอบนี้</span><input id="receiveCost" type="number" min="0" step="0.01"></label><label class="field"><span>วันที่และเวลา</span><input id="receiveDate" type="datetime-local"></label><label class="field"><span>หมายเหตุ/ผู้ขาย</span><input id="receiveNote"></label></div><button class="btn primary" id="receiveSave">รับเข้าสต๊อก</button><div id="receiveSummary"></div>`;let now=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('#receiveDate').value=now;function unitFor(){let k=$('#receiveGroup').value;$('#receiveUnit').value=k==='crab'?'piece':'kg'}$('#receiveGroup').onchange=unitFor;unitFor();$('#receiveSave').onclick=saveReceipt;$('#receiveSummary').innerHTML=Object.entries(db.stockGroups).map(([k,g])=>`<div class="line"><span>${g.name}</span><b>${g.baseUnit==='กรัม'?(g.qty/1000).toFixed(3)+' กก.':g.qty+' '+g.baseUnit}</b></div>`).join('')};
function saveReceipt(){let key=$('#receiveGroup').value,g=db.stockGroups[key],q=+$('#receiveQty').value,cost=+$('#receiveCost').value||0,u=$('#receiveUnit').value;if(!(q>0))return toast('กรุณากรอกจำนวนรับเข้า');let base=u==='kg'?q*1000:u==='khid'?q*100:q;g.qty+=base;let receipt={id:Date.now(),date:new Date($('#receiveDate').value).toISOString(),stockGroup:key,product:g.name,qty:q,unit:u,cost,note:$('#receiveNote').value.trim()};db.stockReceipts.push(receipt);if(cost>0){let related=db.products.filter(p=>p.stockGroup===key),costPerBase=cost/base;related.forEach(p=>p.cost=costPerBase*p.baseQty)}db.logs.push({date:receipt.date,action:`รับเข้า ${g.name} ${q} ${u} ต้นทุน ${cost}`});syncGroupStocks();save();renderAll();toast('รับสินค้าเข้าสต๊อกแล้ว')}
renderAll();
