db.stockGroups=db.stockGroups||{crab:{name:'ปูจ๋า',qty:70,baseUnit:'กระดอง'},fish:{name:'ปลาแห้ง',qty:500,baseUnit:'กรัม'}};
let cp1=db.products.find(p=>p.id===1),cp2=db.products.find(p=>p.id===2),fp=db.products.find(p=>p.id===3);if(cp1)Object.assign(cp1,{stockGroup:'crab',baseQty:1,unit:'กระดอง'});if(cp2)Object.assign(cp2,{stockGroup:'crab',baseQty:7,unit:'แพ็ก 7 กระดอง'});if(fp)Object.assign(fp,{stockGroup:'fish',baseQty:500,unit:'แพ็ก 500 กรัม'});
function syncGroupStocks(){db.products.forEach(p=>{if(p.stockGroup&&db.stockGroups[p.stockGroup])p.stock=Math.floor((db.stockGroups[p.stockGroup].qty+1e-9)/p.baseQty)})}syncGroupStocks();save();
$('#productUnit').closest('label').insertAdjacentHTML('afterend','<label class="field"><span>ผูกกับสต๊อกกลาง</span><select id="stockGroup"><option value="">ไม่ผูก</option><option value="crab">ปูจ๋า (กระดอง)</option><option value="fish">ปลาแห้ง (กรัม)</option></select></label><label class="field"><span>ปริมาณที่ตัดต่อ 1 หน่วยขาย</span><input id="baseQty" type="number" min="0.001" step="0.001" value="1"></label><label class="field"><span>หน่วยปริมาณ</span><select id="saleMeasure"><option value="g">กรัม</option><option value="kg">กิโลกรัม</option><option value="piece">กระดอง/ชิ้น</option></select></label>');
let openBase=openProduct;openProduct=id=>{openBase(id);let p=db.products.find(x=>x.id===id);$('#stockGroup').value=p?.stockGroup||'';let q=p?.baseQty||1;if(p?.stockGroup==='fish'&&q>=1000&&q%1000===0){$('#saleMeasure').value='kg';$('#baseQty').value=q/1000}else{$('#saleMeasure').value=p?.stockGroup==='fish'?'g':'piece';$('#baseQty').value=q}};
let saveProductBase=$('#saveProduct').onclick;$('#saveProduct').onclick=()=>{let oldId=+$('#productId').value,group=$('#stockGroup').value,measure=$('#saleMeasure').value,q=+$('#baseQty').value||1;saveProductBase();let p=db.products.find(x=>x.id===oldId)||(oldId?null:db.products.at(-1));if(p){p.stockGroup=group||'';p.baseQty=measure==='kg'?q*1000:q;if(group==='fish')p.unit=`แพ็ก ${q} ${measure==='kg'?'กิโลกรัม':'กรัม'}`;syncGroupStocks();save();renderAll()}};
let renderProductsBase=renderProducts;renderProducts=()=>{syncGroupStocks();renderProductsBase()};let renderStockBase=renderStock;renderStock=()=>{syncGroupStocks();renderStockBase();let info=document.querySelector('#groupStockInfo');if(!info){$('#stockCards').insertAdjacentHTML('afterend','<div class="box" id="groupStockInfo"></div>');info=$('#groupStockInfo')}let c=db.stockGroups.crab,f=db.stockGroups.fish;info.innerHTML=`<h3>สต๊อกกลางสัมพันธ์กัน</h3><div class="line"><span>ปูจ๋ารวม</span><b>${c.qty} กระดอง (${Math.floor(c.qty/7)} แพ็ก เหลือเศษ ${c.qty%7})</b></div><div class="line"><span>ปลาแห้งรวม</span><b>${f.qty.toLocaleString()} กรัม (${(f.qty/1000).toFixed(3)} กก.)</b></div><div class="actions"><button class="btn secondary" id="setCrabStock">รับเข้า/ปรับปูจ๋า</button><button class="btn secondary" id="setFishStock">รับเข้า/ปรับปลาแห้ง</button></div>`;$('#setCrabStock').onclick=()=>setGroupStock('crab');$('#setFishStock').onclick=()=>setGroupStock('fish')};
function setGroupStock(key){let g=db.stockGroups[key],unit=key==='fish'?prompt('หน่วยที่กรอก: g หรือ kg','kg'):'piece',v=prompt(`จำนวนสต๊อกรวมใหม่ (${unit==='kg'?'กิโลกรัม':g.baseUnit})`,unit==='kg'?g.qty/1000:g.qty);if(v===null||isNaN(v)||+v<0)return;g.qty=unit==='kg'?+v*1000:+v;db.logs.push({date:new Date().toISOString(),action:`ปรับสต๊อกกลาง ${g.name} เป็น ${g.qty} ${g.baseUnit}`});syncGroupStocks();save();renderAll()}
let addBase=add;add=id=>{let p=db.products.find(x=>x.id===id);if(p?.stockGroup){let used=cart.filter(x=>x.stockGroup===p.stockGroup).reduce((s,x)=>s+x.baseQty*x.qty,0),remain=db.stockGroups[p.stockGroup].qty-used;if(remain<p.baseQty)return toast(`สินค้าไม่พอ เหลือ ${remain} ${db.stockGroups[p.stockGroup].baseUnit}`)}addBase(id)};
let completeBase2=complete;complete=()=>{let before=Object.fromEntries(Object.entries(db.stockGroups).map(([k,v])=>[k,v.qty])),used={};cart.forEach(x=>{if(x.stockGroup)used[x.stockGroup]=(used[x.stockGroup]||0)+x.baseQty*x.qty});let count=db.orders.length;completeBase2();if(db.orders.length>count){for(let k in used)db.stockGroups[k].qty=Math.max(0,before[k]-used[k]);syncGroupStocks();save();renderAll()}};setTimeout(()=>{$('#confirmPay').onclick=complete},0);
printReceipt=()=>{};
let reportMode='month',reportCursor=new Date();$('#report .top').insertAdjacentHTML('afterend','<div class="box" id="periodBar"><div class="top"><select id="reportPeriod"><option value="day">รายวัน</option><option value="month" selected>รายเดือน</option><option value="year">รายปี</option></select><button class="btn secondary" id="periodPrev">←</button><b id="periodLabel"></b><button class="btn secondary" id="periodNext">→</button><button class="btn secondary" id="periodNow">ปัจจุบัน</button></div></div>');
function range(){let d=new Date(reportCursor),s,e,label;if(reportMode==='day'){s=new Date(d.getFullYear(),d.getMonth(),d.getDate());e=new Date(s);e.setDate(e.getDate()+1);label=s.toLocaleDateString('th-TH',{dateStyle:'long'})}else if(reportMode==='year'){s=new Date(d.getFullYear(),0,1);e=new Date(d.getFullYear()+1,0,1);label='ปี '+(d.getFullYear()+543)}else{s=new Date(d.getFullYear(),d.getMonth(),1);e=new Date(d.getFullYear(),d.getMonth()+1,1);label=s.toLocaleDateString('th-TH',{month:'long',year:'numeric'})}return{s,e,label}}
renderReports=()=>{let r=range(),os=db.orders.filter(o=>new Date(o.date)>=r.s&&new Date(o.date)<r.e),sales=os.reduce((s,o)=>s+o.total,0),cost=os.reduce((s,o)=>s+o.items.reduce((a,x)=>a+x.cost*x.qty,0),0),exp=db.expenses.filter(x=>new Date(x.date)>=r.s&&new Date(x.date)<r.e).reduce((s,x)=>s+x.amount,0);$('#salesToday').textContent=money(sales);$('#orderCount').textContent=os.length;$('#profit').textContent=money(sales-cost-exp);$('#periodLabel').textContent=r.label;$('#history').innerHTML=os.slice().reverse().map(o=>`<div class="line"><div><b>${o.no}</b><div>${new Date(o.date).toLocaleString('th-TH')} · ${o.payment}</div></div><b>${money(o.total)}</b></div>`).join('')||'ไม่มีรายการในช่วงนี้'};
$('#reportPeriod').onchange=e=>{reportMode=e.target.value;reportCursor=new Date();renderReports()};function move(n){if(reportMode==='day')reportCursor.setDate(reportCursor.getDate()+n);else if(reportMode==='month')reportCursor.setMonth(reportCursor.getMonth()+n);else reportCursor.setFullYear(reportCursor.getFullYear()+n);renderReports()}$('#periodPrev').onclick=()=>move(-1);$('#periodNext').onclick=()=>move(1);$('#periodNow').onclick=()=>{reportCursor=new Date();renderReports()};renderAll();
