document.body.insertAdjacentHTML('beforeend','<div class="modal" id="josDialog"><div class="dialog" style="max-width:420px"><h2 id="josDialogTitle">JOS POS</h2><p id="josDialogMessage" style="white-space:pre-line"></p><label class="field" id="josInputWrap" hidden><input id="josDialogInput"></label><div class="actions"><button class="btn secondary" id="josDialogCancel">ยกเลิก</button><button class="btn primary" id="josDialogOk">ตกลง</button></div></div></div>');
function josDialog(message,{title='JOS POS',input=false,value='',cancel=false}={}){return new Promise(resolve=>{let m=$('#josDialog');$('#josDialogTitle').textContent=title;$('#josDialogMessage').textContent=message;$('#josInputWrap').hidden=!input;$('#josDialogInput').value=value;$('#josDialogCancel').hidden=!cancel;m.classList.add('show');if(input)setTimeout(()=>$('#josDialogInput').focus(),50);let done=v=>{m.classList.remove('show');resolve(v)};$('#josDialogOk').onclick=()=>done(input?$('#josDialogInput').value:true);$('#josDialogCancel').onclick=()=>done(input?null:false)})}
async function josSuccess(message){return josDialog(message,{title:'✅ สำเร็จ'})}
$('#clear').onclick=async()=>{if(!cart.length)return;if(await josDialog('ต้องการยกเลิกออเดอร์นี้หรือไม่?',{title:'ยืนยันการยกเลิก',cancel:true})){cart=[];renderCart();await josSuccess('ยกเลิกออเดอร์เรียบร้อยแล้ว')}};
$('#discountBtn').onclick=async()=>{let v=await josDialog('กรอกส่วนลดทั้งบิล (บาท)',{title:'ส่วนลด',input:true,value:String(orderDiscount),cancel:true});if(v!==null&&!isNaN(v)&&+v>=0){orderDiscount=+v;renderCart()}};
$('#orderNoteBtn').onclick=async()=>{let v=await josDialog('กรอกหมายเหตุออเดอร์',{title:'หมายเหตุ',input:true,value:orderNote,cancel:true});if(v!==null)orderNote=v.trim()};
adjustProductStock=async id=>{let p=db.products.find(x=>x.id===id),v=await josDialog(`ยอดคงเหลือใหม่ของ ${p.name} (${p.unit||'ชิ้น'})`,{title:'ปรับสต๊อก',input:true,value:String(p.stock),cancel:true});if(v!==null&&!isNaN(v)&&+v>=0){p.stock=+v;db.logs.push({date:new Date().toISOString(),action:`ปรับสต๊อก ${p.name} เป็น ${v}`});save();renderAll();await josSuccess('ปรับสต๊อกเรียบร้อยแล้ว')}};
$('#deleteProduct').onclick=async()=>{let id=+$('#productId').value,p=db.products.find(x=>x.id===id);if(p&&await josDialog(`ต้องการลบสินค้า “${p.name}” หรือไม่?`,{title:'ยืนยันการลบ',cancel:true})){db.products=db.products.filter(x=>x.id!==id);save();$('#productModal').classList.remove('show');renderAll();await josSuccess('ลบสินค้าเรียบร้อยแล้ว')}};
let exportAction=$('#exportBtn').onclick;$('#exportBtn').onclick=async()=>{exportAction();await josSuccess('สร้างไฟล์สำรอง .jos เรียบร้อยแล้ว\nตรวจสอบไฟล์ได้ในโฟลเดอร์ดาวน์โหลด')};
let csvAction=$('#csvBtn').onclick;$('#csvBtn').onclick=async()=>{csvAction();await josSuccess('Export รายงานยอดขาย CSV เรียบร้อยแล้ว')};
$('#importFile').onchange=async e=>{try{let file=e.target.files[0];if(!file)return;let x=JSON.parse(await file.text());if(x.format!=='JOS-POS'||!x.data)throw 0;let ok=await josDialog(`พบสินค้า ${x.data.products?.length||0} รายการ และยอดขาย ${x.data.orders?.length||0} บิล\nต้องการนำเข้าข้อมูลหรือไม่?`,{title:'ยืนยัน Import',cancel:true});if(!ok)return;localStorage.setItem('jos-pos-auto-backup',JSON.stringify(db));db=x.data;save();await josSuccess('Import ข้อมูลเรียบร้อยแล้ว\nระบบจะเปิดใหม่เพื่อโหลดข้อมูล');location.reload()}catch{await josDialog('ไฟล์ .jos ไม่ถูกต้องหรืออ่านไม่ได้',{title:'เกิดข้อผิดพลาด'})}finally{e.target.value=''}};
let settingsAction=$('#saveSettings').onclick;$('#saveSettings').onclick=async()=>{settingsAction();await josSuccess('บันทึกการตั้งค่าเรียบร้อยแล้ว')};
let expenseAction=$('#addExpense').onclick;$('#addExpense').onclick=async()=>{let before=db.expenses.length;expenseAction();if(db.expenses.length>before)await josSuccess('บันทึกรายจ่ายเรียบร้อยแล้ว')};
let receiveAction=$('#receiveSave')?.onclick;if(receiveAction)$('#receiveSave').onclick=async()=>{let before=db.stockReceipts.length;receiveAction();if(db.stockReceipts.length>before)await josSuccess('รับสินค้าเข้าสต๊อกเรียบร้อยแล้ว')};
let financeDialogBase=renderFinance;renderFinance=()=>{financeDialogBase();$$('[data-del-exp]').forEach(b=>b.onclick=async()=>{if(await josDialog('ต้องการลบรายจ่ายรายการนี้หรือไม่?',{title:'ยืนยันการลบ',cancel:true})){db.expenses=db.expenses.filter(x=>x.id!=b.dataset.delExp);save();renderFinance();await josSuccess('ลบรายจ่ายเรียบร้อยแล้ว')}})};renderFinance();
